# Generated by Django 4.2.29 on 2026-03-23 17:38

from django.conf import settings
import django.contrib.postgres.indexes
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tcf_website", "0028_schedule_share_token_schedulebookmark_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lab",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pi_name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("research_areas", models.TextField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("office", models.CharField(blank=True, max_length=255)),
                ("photo_url", models.CharField(blank=True, max_length=512)),
                ("profile_url", models.URLField(blank=True)),
                ("google_scholar", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("education", models.TextField(blank=True)),
                ("is_recruiting", models.BooleanField(default=False)),
                (
                    "combined_search_text",
                    models.CharField(blank=True, editable=False, max_length=1024),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcf_website.department",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabReview",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "overall",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "mentorship",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "work_life",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "friendliness",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "inclusivity",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "responsiveness",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                (
                    "hours_per_week",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(80),
                        ]
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("undergrad_ra", "Undergraduate RA"),
                            ("grad_ra", "Graduate RA"),
                            ("postdoc", "Postdoc"),
                            ("staff", "Staff"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("period", models.CharField(max_length=100)),
                ("how_joined", models.TextField(blank=True)),
                ("advice", models.TextField(blank=True)),
                ("would_recommend", models.BooleanField(default=True)),
                ("text", models.TextField(blank=True)),
                ("hidden", models.BooleanField(default=False)),
                ("toxicity_rating", models.IntegerField(default=0)),
                ("toxicity_category", models.CharField(blank=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "lab",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcf_website.lab",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LabVote",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(-1),
                            django.core.validators.MaxValueValidator(1),
                        ]
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tcf_website.labreview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["review"], name="tcf_website_review__1ab091_idx"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="labvote",
            constraint=models.UniqueConstraint(
                fields=("user", "review"), name="unique lab vote per user and review"
            ),
        ),
        migrations.AddIndex(
            model_name="labreview",
            index=models.Index(fields=["lab"], name="tcf_website_lab_id_412102_idx"),
        ),
        migrations.AddIndex(
            model_name="labreview",
            index=models.Index(
                fields=["user", "-created"], name="tcf_website_user_id_6a3035_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="lab",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["combined_search_text"],
                name="lab_combined_search_text",
                opclasses=["gin_trgm_ops"],
            ),
        ),
    ]
